# Generated by Django 4.1.7 on 2023-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="number",
            field=models.CharField(max_length=150, verbose_name="Maktab raqami"),
        ),
    ]
